package:
  name: saxsfittool
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - setuptools
    - pyqt >=5
    - setuptools_scm
    - matplotlib
    - numpy
    - scipy
    - cython
    - sastool >=1.0.5

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pyqt >=5
    - sastool >=1.0.5

about:
  home: https://github.com/awacha/saxsfittool
  license: 3-clause BSD license
  dev_url: https://github.com/awacha/saxsfittool.git
  license_family: BSD
  license_file: LICENSE
  summary: Fitting models to SAXS curves
  description: A GUI utility for nonlinear least-squares fitting of various models to small-angle X-ray scattering curves or other experimental results

app:
  entry: saxsfittool   [linux]
  entry: saxsfittool   [win]
  summary: A GUI utility for nonlinear least-squares fitting of various models to small-angle X-ray scattering curves or other experimental results
  type: desk
#  icon: tem_circlefind.png
