# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/saxsfittool/resource/saxsfittool.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(746, 446)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputdata_box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputdata_box.sizePolicy().hasHeightForWidth())
        self.inputdata_box.setSizePolicy(sizePolicy)
        self.inputdata_box.setObjectName("inputdata_box")
        self.gridLayout = QtWidgets.QGridLayout(self.inputdata_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.inputdata_box)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.inputdata_box)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.maximumXDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.inputdata_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximumXDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.maximumXDoubleSpinBox.setSizePolicy(sizePolicy)
        self.maximumXDoubleSpinBox.setDecimals(4)
        self.maximumXDoubleSpinBox.setObjectName("maximumXDoubleSpinBox")
        self.gridLayout.addWidget(self.maximumXDoubleSpinBox, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.inputdata_box)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.minimumXDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.inputdata_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimumXDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.minimumXDoubleSpinBox.setSizePolicy(sizePolicy)
        self.minimumXDoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.minimumXDoubleSpinBox.setDecimals(4)
        self.minimumXDoubleSpinBox.setObjectName("minimumXDoubleSpinBox")
        self.gridLayout.addWidget(self.minimumXDoubleSpinBox, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.inputdata_box)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.openButton = QtWidgets.QPushButton(self.inputdata_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.openButton.setIcon(icon)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 0, 2, 1, 2)
        self.plotModeComboBox = QtWidgets.QComboBox(self.inputdata_box)
        self.plotModeComboBox.setObjectName("plotModeComboBox")
        self.gridLayout.addWidget(self.plotModeComboBox, 3, 2, 1, 2)
        self.setLimitsFromZoomPushButton = QtWidgets.QPushButton(self.inputdata_box)
        self.setLimitsFromZoomPushButton.setObjectName("setLimitsFromZoomPushButton")
        self.gridLayout.addWidget(self.setLimitsFromZoomPushButton, 1, 3, 2, 1)
        self.verticalLayout.addWidget(self.inputdata_box)
        self.fitcontrol_box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitcontrol_box.sizePolicy().hasHeightForWidth())
        self.fitcontrol_box.setSizePolicy(sizePolicy)
        self.fitcontrol_box.setObjectName("fitcontrol_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fitcontrol_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fitFunctionComboBox = QtWidgets.QComboBox(self.fitcontrol_box)
        self.fitFunctionComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.fitFunctionComboBox.setObjectName("fitFunctionComboBox")
        self.gridLayout_2.addWidget(self.fitFunctionComboBox, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.fitcontrol_box)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.executePushButton = QtWidgets.QPushButton(self.fitcontrol_box)
        self.executePushButton.setObjectName("executePushButton")
        self.gridLayout_2.addWidget(self.executePushButton, 1, 1, 1, 1)
        self.rePlotPushButton = QtWidgets.QPushButton(self.fitcontrol_box)
        self.rePlotPushButton.setObjectName("rePlotPushButton")
        self.gridLayout_2.addWidget(self.rePlotPushButton, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.fitcontrol_box)
        self.parameters_box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters_box.sizePolicy().hasHeightForWidth())
        self.parameters_box.setSizePolicy(sizePolicy)
        self.parameters_box.setObjectName("parameters_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.parameters_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.parameters_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 274, 126))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setRootIsDecorated(False)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setItemsExpandable(False)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_4.addWidget(self.treeView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.parameters_box)
        self.horizontalLayout.addWidget(self.frame)
        self.figure_widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figure_widget.sizePolicy().hasHeightForWidth())
        self.figure_widget.setSizePolicy(sizePolicy)
        self.figure_widget.setMinimumSize(QtCore.QSize(400, 0))
        self.figure_widget.setObjectName("figure_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.figure_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.figureLayout = QtWidgets.QVBoxLayout()
        self.figureLayout.setObjectName("figureLayout")
        self.verticalLayout_3.addLayout(self.figureLayout)
        self.horizontalLayout.addWidget(self.figure_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SAXS Fit Tool"))
        self.inputdata_box.setTitle(_translate("Form", "Input data"))
        self.label_2.setText(_translate("Form", "Minimum x:"))
        self.label.setText(_translate("Form", "File:"))
        self.label_3.setText(_translate("Form", "Maximum x:"))
        self.label_5.setText(_translate("Form", "Plot mode:"))
        self.openButton.setText(_translate("Form", "Open"))
        self.setLimitsFromZoomPushButton.setText(_translate("Form", "Set from\n"
"zoom"))
        self.fitcontrol_box.setTitle(_translate("Form", "Fit control"))
        self.label_4.setText(_translate("Form", "Model function:"))
        self.executePushButton.setText(_translate("Form", "Execute"))
        self.rePlotPushButton.setText(_translate("Form", "Replot"))
        self.parameters_box.setTitle(_translate("Form", "Fit parameters"))

