# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saxsfittool.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(481, 446)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputdata_box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputdata_box.sizePolicy().hasHeightForWidth())
        self.inputdata_box.setSizePolicy(sizePolicy)
        self.inputdata_box.setObjectName("inputdata_box")
        self.gridLayout = QtWidgets.QGridLayout(self.inputdata_box)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.inputdata_box)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.inputdata_box)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.maximumXDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.inputdata_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximumXDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.maximumXDoubleSpinBox.setSizePolicy(sizePolicy)
        self.maximumXDoubleSpinBox.setObjectName("maximumXDoubleSpinBox")
        self.gridLayout.addWidget(self.maximumXDoubleSpinBox, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.inputdata_box)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.openButton = QtWidgets.QPushButton(self.inputdata_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButton.sizePolicy().hasHeightForWidth())
        self.openButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.openButton.setIcon(icon)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 0, 2, 1, 1)
        self.minimumXDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.inputdata_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimumXDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.minimumXDoubleSpinBox.setSizePolicy(sizePolicy)
        self.minimumXDoubleSpinBox.setObjectName("minimumXDoubleSpinBox")
        self.gridLayout.addWidget(self.minimumXDoubleSpinBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.inputdata_box)
        self.fitcontrol_box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitcontrol_box.sizePolicy().hasHeightForWidth())
        self.fitcontrol_box.setSizePolicy(sizePolicy)
        self.fitcontrol_box.setObjectName("fitcontrol_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fitcontrol_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.fitcontrol_box)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.fitcontrol_box)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.fitcontrol_box)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.fitcontrol_box)
        self.parameters_box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters_box.sizePolicy().hasHeightForWidth())
        self.parameters_box.setSizePolicy(sizePolicy)
        self.parameters_box.setObjectName("parameters_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.parameters_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.parameters_box)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 399, 152))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.treeView = QtWidgets.QTreeView(self.scrollAreaWidgetContents)
        self.treeView.setUniformRowHeights(True)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_4.addWidget(self.treeView)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.parameters_box)
        self.horizontalLayout.addWidget(self.frame)
        self.figure_widget = QtWidgets.QWidget(Form)
        self.figure_widget.setObjectName("figure_widget")
        self.frame.raise_()
        self.horizontalLayout.addWidget(self.figure_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SAXS Fit Tool"))
        self.inputdata_box.setTitle(_translate("Form", "Input data"))
        self.label_2.setText(_translate("Form", "Minimum x:"))
        self.label.setText(_translate("Form", "File:"))
        self.label_3.setText(_translate("Form", "Maximum x:"))
        self.openButton.setText(_translate("Form", "Open"))
        self.fitcontrol_box.setTitle(_translate("Form", "Fit control"))
        self.label_4.setText(_translate("Form", "Model function:"))
        self.pushButton.setText(_translate("Form", "Execute"))
        self.parameters_box.setTitle(_translate("Form", "Fit parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

